name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies
        run: |
          cd webapp/React/forcasttx  # Navigate to the directory containing package.json
          npm ci

      #- name: Run ESLint
#        run: |
        #  cd webapp/React/forcasttx  # Navigate to the directory containing package.json
       #   npm run lint
          
      - name: Run Code Review with ChatGPT
        run: |
         cd webapp/js
         node reviewCode.js  # Assuming reviewCode.js is the script you created above
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }} 
     
      - name: Build React App
        run: |
          cd webapp/React/forcasttx  # Navigate to the directory containing package.json
          npm run build
      - name: start React App
        run: |
          cd webapp/React/forcasttx  # Navigate to the directory containing package.json
          npm start
